name: Tony Confrey
footer-links:
  email: tconfrey@gmail.com
theme: jekyll-theme-cayman
github:
  is_project_page: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: BrainTool - Beyond Bookmarks
tagline: The Topic Manager for your Online Life
description: Tame your tabs, control your browser! Tag and link your online info to see it organized and annotated in the side panel. Control your browser tabs from there.
url: https://braintool.org
logo: /site/logo.png
# Google Analytics
google_analytics: UA-184551494-1
defaults:
  -
    scope:
      path:            "versions/*"
    values:
      sitemap:         false